# Generated by Django 5.2.5 on 2025-09-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
